server:
  port: 8082
  tomcat:
          max-threads: 100

spring:
  application:
    name: demoCampaignRESTSvc

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true
